<script lang="ts">
  import { 
    ChevronRight,
    Clock,
    CheckCircle2,
    Send,
    AlertTriangle,
    Search
  } from "lucide-svelte";
  import * as Card from "$lib/components/ui/card/index.js";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import { Skeleton } from "$lib/components/ui/skeleton/index.js";
  import { Input } from '$lib/components/ui/input/index.js';
  import { createQuery } from '@tanstack/svelte-query';
  import { queries } from '$lib/api/queries';
  import { SEED_IDS } from '$lib/api/constants';
  import { goto } from '$app/navigation';

  let searchQuery = $state('');
  
  let activeTab = $state<'all' | 'drafted' | 'approved' | 'sent'>('all');

  const reqsQuery = createQuery(() => queries.requisitions(SEED_IDS.MUNICIPALITY_ID));

  let reqs = $derived((reqsQuery.data as any[]) ?? []);
  let filteredReqs = $derived(
    reqs
      .filter((r: any) => activeTab === 'all' || r.status === activeTab)
      .filter((r: any) => !searchQuery || r.rhuName?.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  function accentBorder(status: string): string {
    return status === 'drafted'  ? 'border-l-amber-400'
         : status === 'approved' ? 'border-l-blue-500'
         : status === 'sent'     ? 'border-l-emerald-500'
         : 'border-l-zinc-600';
  }

  function formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  }

  function medicineLabel(count: number): string {
    return `${count} ${count === 1 ? 'medicine' : 'medicines'}`;
  }
</script>

<div class="flex flex-col gap-6 flex-1 min-h-0">
  <div class="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Requisitions</h1>
      <p class="text-sm text-muted-foreground mt-1">
        Manage resupply requests generated by threshold breaches across the municipality.
      </p>
    </div>
    <div class="relative w-full sm:w-64">
      <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
      <Input placeholder="Search by RHU name..." bind:value={searchQuery} class="pl-9" />
    </div>
  </div>

  <Card.Root class="flex flex-col flex-1 min-h-0">
    <Card.Header class="pb-0">
      <div class="flex gap-6 border-b">
        {#each [
          { id: 'all',      label: 'All Requests', count: reqs.length },
          { id: 'drafted',  label: 'Drafted',       count: reqs.filter((r: any) => r.status === 'drafted').length },
          { id: 'approved', label: 'Approved',      count: reqs.filter((r: any) => r.status === 'approved').length },
          { id: 'sent',     label: 'Sent to Pharmacy', count: reqs.filter((r: any) => r.status === 'sent').length },
        ] as tab}
          <button
            onclick={() => activeTab = tab.id as any}
            class="text-sm font-medium pb-3 -mb-px transition-colors {activeTab === tab.id ? 'text-foreground border-b-2 border-primary' : 'text-muted-foreground hover:text-foreground'}"
          >{tab.label} ({tab.count})</button>
        {/each}
      </div>
    </Card.Header>
    <Card.Content class="pt-4 flex flex-col flex-1 min-h-0">
      <div class="relative flex-1 min-h-[200px]">

        {#if reqsQuery.isPending}
        <div class="flex flex-col gap-3">
          {#each Array(4) as _}
            <div class="border-l-4 border-l-zinc-700 rounded-md border border-border p-4 flex items-center justify-between gap-4">
              <div class="flex flex-col gap-1.5 flex-1">
                <Skeleton class="h-4 w-28" />
                <Skeleton class="h-3 w-40" />
              </div>
              <div class="flex flex-col gap-1.5 items-center">
                <Skeleton class="h-5 w-20" />
                <Skeleton class="h-3 w-24" />
              </div>
              <div class="flex flex-col gap-1.5 items-end">
                <Skeleton class="h-3 w-24" />
                <Skeleton class="h-8 w-20" />
              </div>
            </div>
          {/each}
        </div>

        {:else if reqsQuery.isError}
          <div class="absolute inset-0 flex flex-col items-center justify-center text-center text-destructive">
            <AlertTriangle class="h-8 w-8 mx-auto mb-3 opacity-80" />
            <p class="text-sm font-medium">Failed to load requisitions.</p>
            <p class="text-xs opacity-70 mt-1">{reqsQuery.error?.message}</p>
          </div>

        {:else if filteredReqs.length === 0}
          {#if searchQuery}
            <div class="absolute inset-0 flex flex-col items-center justify-center text-center text-muted-foreground">
              <p class="text-sm">No results for "<span class="text-foreground">{searchQuery}</span>"</p>
            </div>
          {:else if activeTab === 'drafted'}
            <div class="absolute inset-0 flex flex-col items-center justify-center text-center">
              <p class="text-sm font-medium text-foreground">All caught up</p>
              <p class="text-xs text-muted-foreground mt-1">No pending requisitions require your approval.</p>
            </div>
          {:else}
            <div class="absolute inset-0 flex flex-col items-center justify-center text-center text-muted-foreground">
              <p class="text-sm">No requisitions in this category.</p>
            </div>
          {/if}

        {:else}
          <div class="flex flex-col gap-2">
            {#each filteredReqs as req}
              {@const refNum = `REQ-${req.id.slice(0, 6).toUpperCase()}`}
              {@const count = req.items?.length ?? 0}
              {@const firstMed = req.items?.[0]?.genericName ?? ''}
              <div
                role="button" tabindex="0"
                onclick={() => goto(`/requisitions/${req.id}`)}
                onkeydown={(e) => e.key === 'Enter' && goto(`/requisitions/${req.id}`)}
                class="border-l-4 {accentBorder(req.status)} rounded-md border border-border bg-card hover:bg-muted/30 transition-colors px-5 py-4 flex items-center gap-6 min-h-[72px] cursor-pointer"
              >
                <!-- Col 1: Ref + RHU -->
                <div class="flex flex-col min-w-[140px]">
                  <span class="text-sm font-bold tracking-wide">{refNum}</span>
                  <span class="text-xs text-muted-foreground mt-0.5">{req.rhuName}</span>
                </div>

                <!-- Col 2: Status + medicine info -->
                <div class="flex flex-col flex-1 min-w-0">
                  {#if req.status === 'drafted'}
                    <Badge variant="outline" class="border-amber-400 text-amber-500 gap-1 w-fit text-xs"><Clock class="h-3 w-3" /> Drafted</Badge>
                  {:else if req.status === 'approved'}
                    <Badge variant="outline" class="border-blue-500 text-blue-500 gap-1 w-fit text-xs"><CheckCircle2 class="h-3 w-3" /> Approved</Badge>
                  {:else if req.status === 'sent'}
                    <Badge variant="outline" class="border-emerald-500 text-emerald-500 gap-1 w-fit text-xs"><Send class="h-3 w-3" /> Sent to Pharmacy</Badge>
                  {:else}
                    <Badge variant="outline" class="gap-1 w-fit text-xs">{req.status}</Badge>
                  {/if}
                  <span class="text-xs text-muted-foreground mt-1 truncate">
                    {firstMed ? `${firstMed} · ` : ''}{medicineLabel(count)}
                  </span>
                </div>

                <!-- Col 3: Date + chevron -->
                <div class="flex items-center gap-3 shrink-0">
                  <span class="text-xs text-muted-foreground">Drafted: {formatDate(req.draftedAt)}</span>
                  <ChevronRight class="h-4 w-4 text-muted-foreground/40" />
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </Card.Content>
  </Card.Root>
</div>
