<script lang="ts">
  import { 
    FileText, 
    Filter,
    ChevronRight,
    Clock,
    CheckCircle2,
    Send
  } from "lucide-svelte";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  
  // Mock Data
  const requisitions = [
    { id: "req-1", rhuName: "Barangay San Jose RHU", status: "drafted", itemsCount: 2, draftedAt: "10 mins ago" },
    { id: "req-2", rhuName: "Barangay Mabini RHU", status: "approved", itemsCount: 5, draftedAt: "2 hours ago" },
    { id: "req-3", rhuName: "Barangay Poblacion RHU", status: "sent", itemsCount: 1, draftedAt: "1 day ago" },
    { id: "req-4", rhuName: "Barangay Rizal RHU", status: "drafted", itemsCount: 3, draftedAt: "5 mins ago" },
  ];
</script>

<div class="flex flex-col gap-6">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Requisitions</h1>
      <p class="text-sm text-muted-foreground mt-1">
        Manage resupply requests generated by threshold breaches across the municipality.
      </p>
    </div>
    <div class="flex gap-2">
      <Button variant="outline" class="gap-2"><Filter class="h-4 w-4" /> Filter</Button>
    </div>
  </div>

  <Card.Root>
    <Card.Header>
      <div class="flex gap-4 border-b pb-4 mb-4">
        <div class="text-sm font-medium text-foreground border-b-2 border-primary pb-4 -mb-[18px]">All Requests</div>
        <div class="text-sm font-medium text-muted-foreground pb-4 cursor-pointer hover:text-foreground">Drafted (2)</div>
        <div class="text-sm font-medium text-muted-foreground pb-4 cursor-pointer hover:text-foreground">Approved (1)</div>
        <div class="text-sm font-medium text-muted-foreground pb-4 cursor-pointer hover:text-foreground">Sent to PHO (1)</div>
      </div>
    </Card.Header>
    <Card.Content>
      <Table.Root>
        <Table.Header>
          <Table.Row>
            <Table.Head>Requisition ID</Table.Head>
            <Table.Head>RHU</Table.Head>
            <Table.Head>Status</Table.Head>
            <Table.Head>Medicines</Table.Head>
            <Table.Head>Drafted</Table.Head>
            <Table.Head class="text-right">Actions</Table.Head>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {#each requisitions as req}
            <Table.Row>
              <Table.Cell class="font-medium font-mono text-muted-foreground text-xs">{req.id}</Table.Cell>
              <Table.Cell class="font-medium">{req.rhuName}</Table.Cell>
              <Table.Cell>
                {#if req.status === 'drafted'}
                  <Badge variant="outline" class="border-amber-500 text-amber-600 gap-1"><Clock class="h-3 w-3"/> Drafted</Badge>
                {:else if req.status === 'approved'}
                  <Badge variant="outline" class="border-emerald-500 text-emerald-600 gap-1"><CheckCircle2 class="h-3 w-3"/> Approved</Badge>
                {:else if req.status === 'sent'}
                  <Badge variant="outline" class="border-blue-500 text-blue-600 gap-1"><Send class="h-3 w-3"/> Sent to PHO</Badge>
                {/if}
              </Table.Cell>
              <Table.Cell>{req.itemsCount} items</Table.Cell>
              <Table.Cell class="text-muted-foreground">{req.draftedAt}</Table.Cell>
              <Table.Cell class="text-right">
                <Button variant="ghost" size="sm" href="/requisitions/{req.id}">
                  Review <ChevronRight class="h-4 w-4 ml-1" />
                </Button>
              </Table.Cell>
            </Table.Row>
          {/each}
        </Table.Body>
      </Table.Root>
    </Card.Content>
  </Card.Root>
</div>
