<script lang="ts">
  import { 
    Filter,
    ChevronRight,
    Clock,
    CheckCircle2,
    Send
  } from "lucide-svelte";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import type { PageData } from './$types';
  
  let { data }: { data: PageData } = $props();

  let activeTab = $state<'all' | 'drafted' | 'approved' | 'sent'>('all');

  let reqs = $derived(data.requisitions);
  let filteredReqs = $derived(
    activeTab === 'all' ? reqs : reqs.filter(r => r.status === activeTab)
  );
</script>

<div class="flex flex-col gap-6">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Requisitions</h1>
      <p class="text-sm text-muted-foreground mt-1">
        Manage resupply requests generated by threshold breaches across the municipality.
      </p>
    </div>
    <div class="flex gap-2">
      <Button variant="outline" class="gap-2"><Filter class="h-4 w-4" /> Filter</Button>
    </div>
  </div>

  <Card.Root>
    <Card.Header>
      <div class="flex gap-4 border-b pb-4 mb-4">
        <button 
          onclick={() => activeTab = 'all'} 
          class="text-sm font-medium pb-4 -mb-[18px] transition-colors {activeTab === 'all' ? 'text-foreground border-b-2 border-primary' : 'text-muted-foreground hover:text-foreground'}"
        >All Requests ({reqs.length})</button>
        
        <button 
          onclick={() => activeTab = 'drafted'} 
          class="text-sm font-medium pb-4 -mb-[18px] transition-colors {activeTab === 'drafted' ? 'text-foreground border-b-2 border-primary' : 'text-muted-foreground hover:text-foreground'}"
        >Drafted ({reqs.filter(r => r.status === 'drafted').length})</button>
        
        <button 
          onclick={() => activeTab = 'approved'} 
          class="text-sm font-medium pb-4 -mb-[18px] transition-colors {activeTab === 'approved' ? 'text-foreground border-b-2 border-primary' : 'text-muted-foreground hover:text-foreground'}"
        >Approved ({reqs.filter(r => r.status === 'approved').length})</button>

        <button 
          onclick={() => activeTab = 'sent'} 
          class="text-sm font-medium pb-4 -mb-[18px] transition-colors {activeTab === 'sent' ? 'text-foreground border-b-2 border-primary' : 'text-muted-foreground hover:text-foreground'}"
        >Sent to PHO ({reqs.filter(r => r.status === 'sent').length})</button>
      </div>
    </Card.Header>
    <Card.Content>
      <Table.Root>
        <Table.Header>
          <Table.Row>
            <Table.Head>Requisition ID</Table.Head>
            <Table.Head>RHU</Table.Head>
            <Table.Head>Status</Table.Head>
            <Table.Head>Medicines</Table.Head>
            <Table.Head>Drafted</Table.Head>
            <Table.Head class="text-right">Actions</Table.Head>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {#each filteredReqs as req}
            <Table.Row>
              <Table.Cell class="font-medium font-mono text-muted-foreground text-xs">{req.id.split('-')[0]}...</Table.Cell>
              <Table.Cell class="font-medium">{req.rhuName}</Table.Cell>
              <Table.Cell>
                {#if req.status === 'drafted'}
                  <Badge variant="outline" class="border-amber-500 text-amber-600 gap-1"><Clock class="h-3 w-3"/> Drafted</Badge>
                {:else if req.status === 'approved'}
                  <Badge variant="outline" class="border-emerald-500 text-emerald-600 gap-1"><CheckCircle2 class="h-3 w-3"/> Approved</Badge>
                {:else if req.status === 'sent'}
                  <Badge variant="outline" class="border-blue-500 text-blue-600 gap-1"><Send class="h-3 w-3"/> Sent to PHO</Badge>
                {:else}
                  <Badge variant="outline" class="gap-1">{req.status}</Badge>
                {/if}
              </Table.Cell>
              <Table.Cell>{req.items?.length || 0} items</Table.Cell>
              <Table.Cell class="text-muted-foreground">{new Date(req.draftedAt).toLocaleDateString()}</Table.Cell>
              <Table.Cell class="text-right">
                <Button variant="ghost" size="sm" href="/requisitions/{req.id}">
                  Review <ChevronRight class="h-4 w-4 ml-1" />
                </Button>
              </Table.Cell>
            </Table.Row>
          {:else}
            <Table.Row>
              <Table.Cell colspan={6} class="text-center text-muted-foreground h-24">No requisitions found.</Table.Cell>
            </Table.Row>
          {/each}
        </Table.Body>
      </Table.Root>
    </Card.Content>
  </Card.Root>
</div>
