import { Resend } from 'resend';
import type { RequisitionPdfData } from '../pdf/requisition-pdf.js';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendRequisitionEmail(
  pdfBuffer: Buffer,
  data: RequisitionPdfData,
): Promise<void> {
  const from = process.env.EMAIL_FROM ?? 'Agap <agap@resend.dev>';
  const to = process.env.EMAIL_TO ?? 'mho@example.com';
  const subject = `[Agap] Medicine Requisition Approved — ${data.rhuName}`;

  const itemLines = data.items
    .map(i => `<li><strong>${i.genericName}</strong>: ${i.quantityRequested} ${i.unit} requested (${i.currentStock} on hand)</li>`)
    .join('\n');

  const html = `
    <h2>Medicine Requisition Approved</h2>
    <p><strong>RHU:</strong> ${data.rhuName}, Barangay ${data.barangay}</p>
    <p><strong>Municipality:</strong> ${data.municipalityName}</p>
    <p><strong>Approved by:</strong> ${data.mhoName ?? 'MHO'}</p>
    <p><strong>Date:</strong> ${data.approvedAt.toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <h3>Requested Medicines</h3>
    <ul>${itemLines}</ul>
    <p>The full requisition form is attached as a PDF.</p>
    <hr/>
    <p style="color:#888;font-size:12px;">Auto-generated by Agap Medicine Stock Intelligence System.</p>
  `;

  const { error } = await resend.emails.send({
    from,
    to,
    subject,
    html,
    attachments: [
      {
        filename: `requisition-${data.id}.pdf`,
        content: pdfBuffer,
      },
    ],
  });

  if (error) {
    throw new Error(`[EMAIL] Resend error: ${error.message}`);
  }

  console.log(`[EMAIL] Requisition ${data.id} sent to ${to}`);
}
